services:
  - type: web
    name: ee-pro-exam-site-2026
    runtime: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
